### ISSUE TITLE
Getting geojson data of the current EU4 map?

### ISSUE THREAD

**Issue by agforero** [nickbabcock/jomini#58]
Title again. Do you know somewhere where I could get geojson (or something similar) of the current EU4 map? Even better, is there a way to derive it from the game files? I thank you again for your help.

**Comment by nickbabcock** [comment]
[Skanderbeg](https://skanderbeg.pm) depicts the EU4 map as geojson. You can see that here in this request: [provinces_1.30.js](https://skanderbeg.pm/provinces_1.30.js). They have a tool (unknown if it is public) that will take the game files and convert to svg so that can be displayed via leaflet. In [Rakaly](https://rakaly.com/eu4), I reconstruct the map from the game files: provinces.bmp and definition.csv but not in a geojson compatible format.

**Comment by agforero** [comment]
Thanks again for your help. I'll have to message the devs of Skanderbeg, see if they can't provide me with the tool they used under the pretense of credit given. This is also in light of the upcoming Leviathan DLC, so I don't want to rely too much on the 1.30 map if it's just going to change in a few days.

Thanks again for your help, and I will give credit where credit is due.
