### ISSUE TITLE
Feature request: Deno support

### ISSUE THREAD

**Issue by shevernitskiy** [nickbabcock/jomini#87]
Hey! Could you add deno support for your lib? It should be easy, cause there are no dependencies.

**Comment by nickbabcock** [comment]
Great idea. I am interested in supporting deno, but I may need some help / insight. While there are no runtime dependencies, there is a code generation step as part of the build process (compiling Rust to Wasm). Since it looks like Deno just hooks into the github repo, do you know if Deno supports some sort of build command to run code generation? Or would I need to commit the build artifacts to the repo?

**Comment by shevernitskiy** [comment]
I think, you could commit wasm module to repo manualy, or doing it in your CI action.
Then just create mod.ts in root folder, wich will bootstrap and expose (exports) your lib.

**Comment by nickbabcock** [comment]
Do you know of any other deno libraries that do that, so I can use them as inspiration? I see a template repo, but it seems to be stalled on a deno issue: https://github.com/flowscripter/template-deno-wasm-rust-library

And yeah I've had my eye on deno for awhile -- haven't taken the plunge yet.

**Comment by shevernitskiy** [comment]
Hm.. I can't remember anything right off the bat.

Here is usual mod.ts https://github.com/denosaurs/netsaur
There you should export functions/classes/types etc from your lib.

What about wasm. You just import it like other file.
like...
```ts
import { parser } from './dist/jomini.wasm'
```

And maybe it will be helpful:
https://github.com/denoland/dnt/
https://deno.com/blog/dnt-oak

**Comment by nickbabcock** [comment]
The good news is that with the latest Deno version the following works with `--allow-read` permissions (as the wasm module is read off the file system):

```ts
import { Jomini } from "npm:jomini@0.8.0";

const data = await Deno.readAll(Deno.stdin);
const parser = await Jomini.initialize();
const out = parser.parseText(
  data,
  { encoding: "windows1252" },
  (query) => query.json(),
);

console.log(out);
```

Ideally, we wouldn't need the `--allow-read` permissions, but Deno is unable to directly import Wasm (https://github.com/denoland/deno/issues/2552), otherwise the following snippet would work:

```ts
import { Jomini } from "npm:jomini@0.8.0/slim";
import wasm from "npm:jomini@0.8.0/jomini.wasm";

const data = Deno.readAll(Deno.stdin);
const parser = await Jomini.initialize({ wasm });
const out = parser.parseText(
  data,
  { encoding: "windows1252" },
  (query) => query.json(),
);

console.log(out);
```

Anything else you are looking for in the initial deno support? If not, I can add this snippet to the readme and close out this issue.

**Comment by shevernitskiy** [comment]
Nice, thanks!
